### ISSUE TITLE
UX Work- User Testing of Beta Orcasite During Soft Release

### ISSUE THREAD

**Issue by UXBrendan** [orcasound/product#108]
**_User Story_**
AS a Orcasound user I WANT a high level of usability of Orcasite SO THAT I can listen to hydrophones in Orcasound's hydrophone network.

**_Description_**
The intent of this story is to user test the beta version of Orcasite that @paulcretu has developed based on the UX Design work submitted to him.

**_Notes:_**
- Contact [@paul](https://orcasound.slack.com/team/U4SGKJVPZ) for access to the beta version of Orcasite for testing
     - Paul will provide what to test and deadline for results
- Please keep [@Scott](https://orcasound.slack.com/team/U4NC3PAG5) in the loop for study progress
- Based on resource limitations, my ([@Brendan](https://orcasound.slack.com/team/USLE291JB)) recommendation is to run a qualitative usability study with a minimum of N=5 participants overall, or N=5 to 8 participants per each of the 3 identified Orcasound personae (New/Infrequent User, Concerned Citizen Scientist, and the Professional Marine Scientist) for a total of N=15 to 18 participants
     - If Orcasite team members can raise funding to use a quantitative usability study platform (e.g. usertesting.com), a quantitative usability study is highly encouraged, as industry standard is to run a quant usability study for products that have a developed beta instance (see [Handbook of Usability Testing: How to Plan, Design, and Conduct Effective Tests, 2nd Edition](https://www.wiley.com/en-us/Handbook+of+Usability+Testing%3A+How+to+Plan%2C+Design%2C+and+Conduct+Effective+Tests%2C+2nd+Edition-p-9781118080405))

**Tasks**
- [ ] Create a study plan for the usability test
- [ ] Request access to the research participant pool in Mailchimp from Brendan
- [ ] Formally present to Paul, Scott, Brendan, and invite all Orcasound members in the [#general](https://orcasound.slack.com/archives/C4MPLUD9R) and [#ux-general](https://orcasound.slack.com/archives/CE5KAK4D6) channels
     - [ ] Record presentation and provide for async review for team members who can't attend

**_Acceptance Criteria_**
GIVEN I use interactive elements within Orcasite WHEN I am using Orcasite to listen to the hydrophones or any other action possible THEN I have the best usability experience possible.

**Comment by PrernaChoubey** [comment]
Hey Brendan,

Can I also work on this issue?

**Comment by UXBrendan** [comment]
@PrernaChoubey 

Reach out to [Darya](https://orcasound.slack.com/team/U04KG7W9UA2) in Slack.

**Comment by Tracer78** [comment]
Hey Brendan - in case this task could use more help, I'm also available to help to get things done quicker

**Comment by Tracer78** [comment]
Hey Brandon - in case this task needs more help, I'm here to help to get it done quicker. I can reach out to Darya if you are okey.
