### ISSUE TITLE
Additional Onboarding Website Content

### ISSUE THREAD

**Issue by UXBrendan** [orcasound/product#74]
Please create a new issue and assign to @UXBrendan documenting any content I need to provide for the onboarding website.
```[tasklist]
### Tasks
- [ ] https://github.com/orcasound/product/issues/82
- [ ] https://github.com/orcasound/product/issues/83
- [ ] https://github.com/orcasound/product/issues/84
- [ ] https://github.com/orcasound/product/issues/85
- [ ] https://github.com/orcasound/product/issues/86
```

**Comment by jeniverede** [comment]
These tasks are content still needed for the onboarding Googlesite, topics Brendan wanted to curate or ask others to work on. 
Jennifer created the tasks. Brendan will assign them.
The person working on each topic would define them.
